### ISSUE TITLE
How to trigger chat via button?

### ISSUE THREAD

**Issue by ovsw** [JodyPSmith/gatsby-plugin-tawk#3]
Thanks for the great plugin! 
I'm trying to make the chat widget appear only when a button is pressed. 
The tawk.to docs say I should use something like this:
```
<a href="javascript:void(Tawk_API.toggle())">Chat</a>
```
However I don't know how to access Tawek_API inside of Gatsby. 

Any help would be greatly appreciated!

**Comment by ovsw** [comment]
thanks to @francocorreasosa for the solution:

```onClick={() => window.Tawk_API.toggle()}```

**Comment by BilalTurabi-786** [comment]
Great @ovsw  .. Thanks for Solution
